server:
  port: 8082

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        enabled: false
        server-addr: localhost:8848
  datasource:
    url: ${JOBPLUS_DB_URL:jdbc:postgresql://localhost:5432/jobplus}
    username: ${JOBPLUS_DB_USERNAME:postgres}
    password: Luo@760818
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
